# The configurations that used for the recording, feel free to edit them
config:

  # Specify a command to be executed
  # like `/bin/bash -l`, `ls`, or any other commands
  # the default is bash for Linux
  # or powershell.exe for Windows
  command: bash -l
  
  # Specify the current working directory path
  # the default is the current working directory path
  cwd: /Users/mordasiewicz
  
  # Export additional ENV variables
  env:
    recording: true
  
  # Explicitly set the number of columns
  # or use `auto` to take the current
  # number of columns of your shell
  cols: 80
  
  # Explicitly set the number of rows
  # or use `auto` to take the current
  # number of rows of your shell
  rows: 34
  
  # Amount of times to repeat GIF
  # If value is -1, play once
  # If value is 0, loop indefinitely
  # If value is a positive number, loop n times
  repeat: -1
  
  # Quality
  # 1 - 100
  quality: 100
  
  # Delay between frames in ms
  # If the value is `auto` use the actual recording delays
  frameDelay: auto
  
  # Maximum delay between frames in ms
  # Ignored if the `frameDelay` isn't set to `auto`
  # Set to `auto` to prevent limiting the max idle time
  maxIdleTime: 2000
  
  # The surrounding frame box
  # The `type` can be null, window, floating, or solid`
  # To hide the title use the value null
  # Don't forget to add a backgroundColor style with a null as type
  frameBox:
    type: window
    title: Terminal
    style:
      border: 0px black solid
      backgroundColor: black
      boxShadow: none
      margin: 0px
  
  # Add a watermark image to the rendered gif
  # You need to specify an absolute path for
  # the image on your machine or a URL, and you can also
  # add your own CSS styles
  watermark:
    imagePath: null
    style:
      position: absolute
      right: 15px
      bottom: 15px
      width: 100px
      opacity: 0.9
  
  # Cursor style can be one of
  # `block`, `underline`, or `bar`
  cursorStyle: block
  
  # Font family
  # You can use any font that is installed on your machine
  # in CSS-like syntax
  fontFamily: "Courier New, Monaco, Lucida Console, Ubuntu Mono, Monospace"
  
  # The size of the font
  fontSize: 14
  
  # The height of lines
  lineHeight: 1
  
  # The spacing between letters
  letterSpacing: 0
  
  # Theme
  theme:
    background: "transparent"
    foreground: "#afafaf"
    cursor: "#c7c7c7"
    black: "#232628"
    red: "#fc4384"
    green: "#b3e33b"
    yellow: "#ffa727"
    blue: "#75dff2"
    magenta: "#ae89fe"
    cyan: "#708387"
    white: "#d5d5d0"
    brightBlack: "#626566"
    brightRed: "#ff7fac"
    brightGreen: "#c8ed71"
    brightYellow: "#ebdf86"
    brightBlue: "#75dff2"
    brightMagenta: "#ae89fe"
    brightCyan: "#b1c6ca"
    brightWhite: "#f9f9f4"
  
records:
  - delay: 0
    content: "\e[00;36m[robin@laptop]\e[00m:\e[00;34m~ $\e[00m\e[0;37m "
  - delay: 816
    content: s
  - delay: 105
    content: s
  - delay: 68
    content: h
  - delay: 100
    content: ' '
  - delay: 112
    content: p
  - delay: 145
    content: i
  - delay: 105
    content: '@'
  - delay: 149
    content: '1'
  - delay: 135
    content: '9'
  - delay: 90
    content: '2'
  - delay: 103
    content: .
  - delay: 65
    content: '1'
  - delay: 207
    content: '6'
  - delay: 142
    content: '8'
  - delay: 172
    content: .
  - delay: 146
    content: '1'
  - delay: 122
    content: .
  - delay: 136
    content: '1'
  - delay: 137
    content: '5'
  - delay: 359
    content: "\r\n"
  - delay: 800
    content: "\r\e[0mpi@192.168.1.15's password: \e[0;37m"
  - delay: 1500
    content: '*'
  - delay: 256
    content: '*'
  - delay: 120
    content: '*'
  - delay: 134
    content: '*'
  - delay: 195
    content: '*'
  - delay: 135
    content: '*'
  - delay: 179
    content: '*'
  - delay: 168
    content: '*'
  - delay: 129
    content: '*'
  - delay: 800
    content: "\e[00m\r\n\r\n"
  - delay: 500
    content: "\e[00;32mpi@raspberrypi\e[00m:\e[00;34m~ $\e[00m\e[0;37m "
  - delay: 1000
    content: s
  - delay: 238
    content: u
  - delay: 128
    content: d
  - delay: 148
    content: o
  - delay: 108
    content: ' '
  - delay: 178
    content: a
  - delay: 228
    content: p
  - delay: 108
    content: t
  - delay: 108
    content: '-'
  - delay: 178
    content: g
  - delay: 128
    content: e
  - delay: 188
    content: t
  - delay: 118
    content: ' '
  - delay: 98
    content: '-'
  - delay: 98
    content: y
  - delay: 108
    content: ' '
  - delay: 98
    content: i
  - delay: 108
    content: n
  - delay: 108
    content: s
  - delay: 148
    content: t
  - delay: 108
    content: a
  - delay: 78
    content: l
  - delay: 138
    content: l
  - delay: 108
    content: ' '
  - delay: 118
    content: a
  - delay: 108
    content: n
  - delay: 138
    content: s
  - delay: 168
    content: i
  - delay: 108
    content: b
  - delay: 128
    content: l
  - delay: 88
    content: e
  - delay: 400
    content: "\e[00m\r\n"
  - delay: 300
    content: "\rReading package lists... 0%\r"
  - delay: 250
    content: "\rReading package lists... 20%\r"
  - delay: 250
    content: "\rReading package lists... 40%\r"
  - delay: 250
    content: "\rReading package lists... 60%\r"
  - delay: 250
    content: "\rReading package lists... 80%\r"
  - delay: 250
    content: "\rReading package lists... 100%\r"
  - delay: 500
    content: "\rReading package lists... Done\r\r\n"
  - delay: 300
    content: "\rBuilding dependency tree... 0%\r"
  - delay: 250
    content: "\rBuilding dependency tree... 20%\r"
  - delay: 250
    content: "\rBuilding dependency tree... 40%\r"
  - delay: 250
    content: "\rBuilding dependency tree... 60%\r"
  - delay: 250
    content: "\rBuilding dependency tree... 80%\r"
  - delay: 250
    content: "\rBuilding dependency tree... 100%\r"
  - delay: 600
    content: "\rBuilding dependency tree... Done\r\r\n"
  - delay: 300
    content: "\rReading state information... 0%\r"
  - delay: 300
    content: "\rReading state information... 20%\r"
  - delay: 300
    content: "\rReading state information... 40%\r"
  - delay: 250
    content: "\rReading state information... 60%\r"
  - delay: 300
    content: "\rReading state information... 80%\r"
  - delay: 500
    content: "\rReading state information... 100%\r"
  - delay: 500
    content: "\rReading state information... Done\r\r\n"
  - delay: 300
    content: "The following NEW packages will be installed:\r\n"
  - delay: 300
    content: "  ansible\r\n"
  - delay: 300
    content: "0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.\r\n"
  - delay: 500
    content: "(Reading database ... \r"
  - delay: 80
    content: "(Reading database ... 5%\r"
  - delay: 80
    content: "(Reading database ... 10%\r"
  - delay: 80
    content: "(Reading database ... 15%\r"
  - delay: 80
    content: "(Reading database ... 20%\r"
  - delay: 80
    content: "(Reading database ... 25%\r"
  - delay: 80
    content: "(Reading database ... 30%\r"
  - delay: 80
    content: "(Reading database ... 35%\r"
  - delay: 80
    content: "(Reading database ... 40%\r"
  - delay: 80
    content: "(Reading database ... 45%\r"
  - delay: 80
    content: "(Reading database ... 50%\r"
  - delay: 80
    content: "(Reading database ... 55%\r"
  - delay: 80
    content: "(Reading database ... 60%\r"
  - delay: 80
    content: "(Reading database ... 65%\r"
  - delay: 80
    content: "(Reading database ... 70%\r"
  - delay: 80
    content: "(Reading database ... 75%\r"
  - delay: 80
    content: "(Reading database ... 80%\r"
  - delay: 80
    content: "(Reading database ... 85%\r"
  - delay: 80
    content: "(Reading database ... 90%\r"
  - delay: 80
    content: "(Reading database ... 95%\r"
  - delay: 80
    content: "(Reading database ... 100%\r"
  - delay: 500
    content: "(Reading database ... Done\r\n"
  - delay: 80
    content: "Setting up ansible (2.7.7+dfsg-1) ...\r\n\r\n"
  - delay: 600
    content: "\e[00;32mpi@raspberrypi\e[00m:\e[00;34m~ $\e[00m \e[0;37m"
  - delay: 600
    content: "c"
  - delay: 120
    content: "u"
  - delay: 152
    content: "r"
  - delay: 100
    content: "l"
  - delay: 100
    content: " "
  - delay: 100
    content: '-'
  - delay: 100
    content: "O"
  - delay: 600
    content: " https://raw.githubusercontent.com/robinmordasiewicz/AV-raspi-config/master/raspi-config.yml\e[00m\n"
  - delay: 10
    content: "\r  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current "
  - delay: 10
    content: "\r\n                                 Dload  Upload   Total   Spent    Left  Speed"
  - delay: 10
    content: "\r\n100 31765  100 31765    0     0   127k      0 --:--:-- --:--:-- --:--:--  127k\r\n\r\n"
  - delay: 600
    content: "\e[00;32mpi@raspberrypi\e[00m:\e[00;34m~ $\e[00m \e[0;37m"
  - delay: 600
    content: a
  - delay: 282
    content: n
  - delay: 177
    content: s
  - delay: 232
    content: i
  - delay: 245
    content: b
  - delay: 305
    content: "\ale"
  - delay: 477
    content: '-'
  - delay: 377
    content: p
  - delay: 64
    content: l
  - delay: 158
    content: 'aybook '
  - delay: 2067
    content: r
  - delay: 155
    content: a
  - delay: 187
    content: s
  - delay: 161
    content: "pi-config.yml\e[0m"
  - delay: 607
    content: "\r\n"
  - delay: 400
    content: "[WARNING]: hosts list is empty. Implicit localhost does not match all\r\n"
  - delay: 0
    content: "\r\n"
  - delay: 0
    content: "Enter settings or press \"Enter\" to accept [defaults]\r\n"
  - delay: 0
    content: "Username:                [pi]:      <--- I am not changing the PI username"
  - delay: 2000
    content: "\rUsername:                [pi]:                                             "
  - delay: 100
    content: "\r\nPassword:         [raspberry]:           <--- I am not changing the password"
  - delay: 2000
    content: "\rPassword:         [raspberry]:                                                 "
  - delay: 0
    content: "\r\nHostname:       [raspberrypi]: "
  - delay: 1250
    content: "\rHostname:       [raspberrypi]: \e[0;37mv\e[0m"
  - delay: 200
    content: "\rHostname:       [raspberrypi]: \e[0;37mvi\e[0m"
  - delay: 250
    content: "\rHostname:       [raspberrypi]: \e[0;37mvid\e[0m"
  - delay: 400
    content: "\rHostname:       [raspberrypi]: \e[0;37mvideo\e[0m"
  - delay: 300
    content: "\rHostname:       [raspberrypi]: \e[0;37mvideopi\e[0m"
  - delay: 1241
    content: "\r\nLanguage Code:  [en_GB.UTF-8]: "
  - delay: 350
    content: "\rLanguage Code:  [en_GB.UTF-8]: \e[0;37me\e[0m"
  - delay: 350
    content: "\rLanguage Code:  [en_GB.UTF-8]: \e[0;37men\e[0m"
  - delay: 150
    content: "\rLanguage Code:  [en_GB.UTF-8]: \e[0;37men_U\e[0m"
  - delay: 250
    content: "\rLanguage Code:  [en_GB.UTF-8]: \e[0;37men_US\e[0m"
  - delay: 450
    content: "\rLanguage Code:  [en_GB.UTF-8]: \e[0;37men_US.\e[0m"
  - delay: 250
    content: "\rLanguage Code:  [en_GB.UTF-8]: \e[0;37men_US.U\e[0m"
  - delay: 550
    content: "\rLanguage Code:  [en_GB.UTF-8]: \e[0;37men_US.UT\e[0m"
  - delay: 350
    content: "\rLanguage Code:  [en_GB.UTF-8]: \e[0;37men_US.UTF\e[0m"
  - delay: 450
    content: "\rLanguage Code:  [en_GB.UTF-8]: \e[0;37men_US.UTF-\e[0m"
  - delay: 250
    content: "\rLanguage Code:  [en_GB.UTF-8]: \e[0;37men_US.UTF-8\e[0m"
  - delay: 600
    content: "\r\nEnable WIFI:            [yes]:                 <--- I am not using WIFI"
  - delay: 1000
    content: "\rEnable WIFI:            [yes]: \e[0;37mn\e[0m               <--- I am not using WIFI"
  - delay: 450
    content: "\rEnable WIFI:            [yes]: \e[0;37mno\e[0m              <--- I am not using WIFI"
  - delay: 1000
    content: "\rEnable WIFI:            [yes]: \e[0;37mno\e[0m                                      \r"
  - delay: 200
    content: "\r\nEnable Bluetooth:       [yes]:                 <--- I am not using bluetooth"
  - delay: 1250
    content: "\rEnable Bluetooth:       [yes]: \e[0;37mn\e[0m               <--- I am not using bluetooth"
  - delay: 450
    content: "\rEnable Bluetooth:       [yes]: \e[0;37mno\e[0m              <--- I am not using bluetooth"
  - delay: 1000
    content: "\rEnable Bluetooth:       [yes]: \e[0;37mno\e[0m                                           \r"
  - delay: 300
    content: "\r\n"
  - delay: 21
    content: "\r\nPLAY [Raspberry PI4 AV Automation] *****************************************\r\n"
  - delay: 450
    content: "TASK [Gathering Facts] *****************************************************\r\n"
  - delay: 0
    content: "\r\n\e[0;32m   The ansible playbook will continue to run, and will reboot the PI4\r\n"
  - delay: 0
    content: "   with Audio/Video players and Bitfocus Companion installed.\e[0m\r\n"
